version: '3.8'
services:
  app:
    container_name: product-app
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=dev
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=productapp
      - DATABASE_PASSWORD=productapp123
      - DATABASE_NAME=productapp
    depends_on:
      - postgres
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=productapp
      - POSTGRES_PASSWORD=productapp123
      - POSTGRES_DB=productapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U productapp']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
