apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productapp
  template:
    metadata:
      labels:
        app: productapp
    spec:
      containers:
        - name: productapp-app
          image: productapp/app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: 'postgres'
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: productapp-service
spec:
  selector:
    app: productapp
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
